steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/arcade-documentation-staging'
      - '.'

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/arcade-documentation-staging'
    # You can add logging options here as well if needed

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'arcade-documentation-staging'
      - '--image'
      - 'gcr.io/$PROJECT_ID/arcade-documentation-staging'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    # You can add logging options here as well if needed

options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

images:
  - 'gcr.io/$PROJECT_ID/arcade-documentation-staging'
