steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'LANDING_PAGE_URL=${_LANDING_PAGE_URL}',
      '--build-arg', 'ADMIN_PAGE_URL=${_ADMIN_PAGE_URL}',
      '--build-arg', 'APP_PAGE_URL=${_APP_PAGE_URL}',
      '--build-arg', 'UNITY_DOCS_URL=${_UNITY_DOCS_URL}',
      '--build-arg', 'POSTHOG_KEY=${_POSTHOG_KEY}',
      '--build-arg', 'POSTHOG_HOST=${_POSTHOG_HOST}',
      '-t', 'gcr.io/$PROJECT_ID/arcade-documentation-staging:$COMMIT_SHA',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/arcade-documentation-staging:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'arcade-documentation-staging'
      - '--image'
      - 'gcr.io/$PROJECT_ID/arcade-documentation-staging:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'LANDING_PAGE_URL=${_LANDING_PAGE_URL},ADMIN_PAGE_URL=${_ADMIN_PAGE_URL},UNITY_DOCS_URL=${_UNITY_DOCS_URL},APP_PAGE_URL=${_APP_PAGE_URL},POSTHOG_KEY=${_POSTHOG_KEY},POSTHOG_HOST=${_POSTHOG_HOST}'

images:
  - 'gcr.io/$PROJECT_ID/arcade-documentation-staging:$COMMIT_SHA'

substitutions:
  _LANDING_PAGE_URL: 'https://staging.luxodd.com'  # Default staging URL, can be overridden in Cloud Build trigger
  _ADMIN_PAGE_URL: 'https://staging-admin.luxodd.com'
  _UNITY_DOCS_URL: 'https://staging-docs.luxodd.com/docs/category/unity-plugin'
  _APP_PAGE_URL: 'https://staging-app.luxodd.com'
  _POSTHOG_KEY: ''  # PostHog API key - intentionally empty for staging (PostHog will be disabled)
  _POSTHOG_HOST: 'https://us.i.posthog.com'  # PostHog host

options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
